/*
Copyright (c) MagiCom Ltd. 2018
 This software is licensed under the MIT license.
 You may obtain a copy of the MIT license here: https://opensource.org/licenses/MIT
 
*/

#ifndef CALLBACKERRORCODES_H
#define CALLBACKERRORCODES_H

#define CALLBACK_ERROR_UNKNOWN 0
#define CALLBACK_ERROR_TIMEOUT_EXPIRED 1
#define CALLBACK_ERROR_COMMUNICATION_ERROR 2
#define CALLBACK_ERROR_READ_PROTECT 3
#define CALLBACK_ERROR_WRITE_PROTECT 4
#define CALLBACK_ERROR_NOT_PROPER_LENGTH 5
#define CALLBACK_ERROR_FLASH_STORAGE_ERROR 6
#define CALLBACK_DH_ERROR 7
#define CALLBACK_ERROR_AES_ERROR 8
#define CALLBACK_ERROR_CANNOT_MALLOC 9
#define CALLBACK_ERROR_COMMUNICATION_BUFFER_FULL 10

#endif /*CALLBACKERRORCODES_H*/